version: 2

updates:
  - package-ecosystem: github-actions
    directory: /
    schedule:
      interval: weekly
      day: monday
      time: "09:00"
      timezone: America/Chicago
    open-pull-requests-limit: 5
    labels:
      - dependencies
      - github-actions
    commit-message:
      prefix: deps
      include: scope
    groups:
      github-actions:
        patterns:
          - "*"

  - package-ecosystem: gomod
    directory: /
    schedule:
      interval: weekly
      day: monday
      time: "09:30"
      timezone: America/Chicago
    open-pull-requests-limit: 5
    labels:
      - dependencies
      - go
    commit-message:
      prefix: deps
      include: scope
    groups:
      go-modules:
        patterns:
          - "*"
